# Config file for [Air](https://github.com/cosmtrek/air) in toml format

# Working directory
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/api/main.go"
bin = "tmp/main"
include_ext = ["go", "tpl", "html", "toml"]
exclude_dir = ["assets", "tmp", "vendor", "test", ".git", "docker", "frontend"]
include_dir = []
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = true
follow_symlink = true
log = "air.log"
poll = false
poll_interval = 0
delay = 500 # ms
stop_on_error = true
send_interrupt = true
kill_delay = 500 # ms

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
